# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: wellofmemories
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
custom:
  video_bucket: dev.wom.com
  dynamo_table: WellOfMemories

provider:
  name: aws
  runtime: python2.7
  environment:
    DYNAMODB_TABLE: ${self:custom.dynamo_table}
    S3_BUCKET: ${self:custom.video_bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Resource: "arn:aws:s3:::${self:custom.video_bucket}/*"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
    - Effect: Allow
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query

resources:
  Resources:
    WellOfMemoriesCounterTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: item
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: item
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    RendersBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"

package:
  include:
    - bin/**
    - src/**
    - assets/**
    - ImageMagick-7.0.7/**
  exclude:
    - requirements.txt
    - serverless.yml
    - README.md
    - LICENSE.txt
    - dependencies-mac/**
    - .TESTS/**
    - ffmpeg/**

functions:
  new_video:
    handler: new_video.handler
    events:
      - http:
          path: new_video/
          method: post
  render_slide:
    handler: render_slide.handler
    timeout: 180
  render_transition:
    handler: render_transition.handler
    timeout: 60
  render_video:
    handler: render_video.handler
    timeout: 300
